config/routes.rb
Rails.application.routes.draw do
  resources :inboxes do
    resources :messages, module: :inboxes      
    end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/inbox.rb
class Inbox < ApplicationRecord
    has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :inbox
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inboxes/messages_controller.rb
class Inboxes::MessagesController < ApplicationController
  before_action :set_inbox
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  def index
    # @messages = Message.all
    @messages = @inbox.messages
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = @inbox.messages.build
    # @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = @inbox.messages.build
    # @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to [@inbox, @messages], notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to [@inbox, @messages], notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to [@inbox, :messages], notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private 
    def set_inbox
      @inbox =Inbox.find(params[:inbox_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      # @message = Message.find(params[:id])
      @message = @inbox.messages.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:title)
    end
end

app/controllers/inboxes_controller.rb
class InboxesController < ApplicationController
  before_action :set_inbox, only: %i[ show edit update destroy ]

  # GET /inboxes or /inboxes.json
  def index
    @inboxes = Inbox.all
  end

  # GET /inboxes/1 or /inboxes/1.json
  def show
  end

  # GET /inboxes/new
  def new
    @inbox = Inbox.new
  end

  # GET /inboxes/1/edit
  def edit
  end

  # POST /inboxes or /inboxes.json
  def create
    @inbox = Inbox.new(inbox_params)

    respond_to do |format|
      if @inbox.save
        format.html { redirect_to inbox_url(@inbox), notice: "Inbox was successfully created." }
        format.json { render :show, status: :created, location: @inbox }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inboxes/1 or /inboxes/1.json
  def update
    respond_to do |format|
      if @inbox.update(inbox_params)
        format.html { redirect_to inbox_url(@inbox), notice: "Inbox was successfully updated." }
        format.json { render :show, status: :ok, location: @inbox }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inboxes/1 or /inboxes/1.json
  def destroy
    @inbox.destroy

    respond_to do |format|
      format.html { redirect_to inboxes_url, notice: "Inbox was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inbox
      @inbox = Inbox.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inbox_params
      params.require(:inbox).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inboxes_helper.rb
module InboxesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/inboxes/_form.html.erb
<%= form_with(model: inbox) do |form| %>
  <% if inbox.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inbox.errors.count, "error") %> prohibited this inbox from being saved:</h2>

      <ul>
        <% inbox.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/inboxes/_inbox.html.erb
<div id="<%= dom_id inbox %>">
  <p>
    <strong>Title:</strong>
    <%= inbox.title %>
  </p>

</div>

app/views/inboxes/edit.html.erb
<h1>Editing inbox</h1>

<%= render "form", inbox: @inbox %>

<br>

<div>
  <%= link_to "Show this inbox", @inbox %> |
  <%= link_to "Back to inboxes", inboxes_path %>
</div>

app/views/inboxes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Inboxes</h1>

<div id="inboxes">
  <% @inboxes.each do |inbox| %>
    <%= render inbox %>
    <p>
      <%= link_to "Show this inbox", inbox %>
    </p>
  <% end %>
</div>

<%= link_to "New inbox", new_inbox_path %>

app/views/inboxes/messages/_form.html.erb
<%= form_with(model: [@inbox, message]) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/inboxes/messages/_message.html.erb
<div id="<%= dom_id message %>">
  <p>
    <strong>Title:</strong>
    <%= message.title %>
  </p>

  <p>
    <strong>Inbox:</strong>
    <%= message.inbox_id %>
  </p>

</div>

app/views/inboxes/messages/edit.html.erb
<h1>Editing message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Show this message", [@inbox,@message] %> |
  <%= link_to "Back to messages", inbox_messages_path(@inbox) %>
</div>

app/views/inboxes/messages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Messages</h1>

<div id="messages">
  <% @messages.each do |message| %>
    <%= render message %>
    <p>
      <%= link_to "Show this message", [@inbox, message] %>
    </p>
  <% end %>
</div>

<%= link_to "New message", new_inbox_message_path %>

app/views/inboxes/messages/new.html.erb
<h1>New message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to messages", inbox_messages_path(@inbox) %>
</div>

app/views/inboxes/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @message %>

<div>
  <%= link_to "Edit this message", edit_inbox_message_path([@inbox,@message]) %> |
  <%= link_to "Back to messages", [@inbox, :messages] %>

  <%= button_to "Destroy this message", [@inbox,@message], method: :delete %>
</div>

app/views/inboxes/new.html.erb
<h1>New inbox</h1>

<%= render "form", inbox: @inbox %>

<br>

<div>
  <%= link_to "Back to inboxes", inboxes_path %>
</div>

app/views/inboxes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @inbox %>

<div>
  <%= link_to "Edit this inbox", edit_inbox_path(@inbox) %> |
  <%= link_to "Back to inboxes", inboxes_path %>

  <%= button_to "Destroy this inbox", @inbox, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nest1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>